apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  creationTimestamp: null
  name: exit-if-newer-build-has-started
spec:
  steps:
  - image: gcr.io/cloud-builders/kubectl
    name: exit-if-newer-build-has-started
    script: |
      #!/usr/bin/env bash
      source .jx/variables.sh
      if [ $(kubectl get pipelineruns.tekton.dev  -l "lighthouse.jenkins-x.io/job=$JOB_NAME,lighthouse.jenkins-x.io/branch=$BRANCH_NAME,lighthouse.jenkins-x.io/buildNum>$BUILD_ID,lighthouse.jenkins-x.io/refs.org=$REPO_OWNER,lighthouse.jenkins-x.io/refs.repo=$REPO_NAME" -oname --no-headers) ]
      then
        echo Newer build exists. Aborting pipeline.
        exit 1
      fi
    resources: {}
    workingDir: /workspace/source
  workspaces:
  - description: The git repo will be cloned onto the volume backing this workspace
    mountPath: /workspace
    name: output
